---
- hosts: all
  name: PHP and Apache2/Httpd Installation and service start
  gather_facts: False
  
  vars_prompt:
    - name: "Version"
      prompt: "what php version to install (5.6/7.0/7.2/all)"
      default: "all"
      private: no

  vars:
    - version: "{{Version}}"

  tasks:

   - name: install python2
     raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python)

   - name: Gathering Facts
     setup:

   - name: Install Apache2 on debian/ubuntu
     become: true
     apt: 
       name: apache2
       state: latest
     vars:
       item:
       - apache2
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

   - name: Install httpd on CentOS/RHEL
     become: true
     yum:
       name: httpd
       state: latest
     vars:
       item:
       - httpd
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
  
   - name: restart apache on debian/ubuntu
     become: true
     service: 
       name: apache2 
       state: started 
       enabled: yes
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

   - name: restart httpd on CentOS/RHEL
     become: true
     service: 
       name: httpd 
       state: started 
       enabled: yes
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'     

# Ubuntu-specific tasks
   - name: PHP | Install Ondrej PHP PPA
     become: true
     apt_repository: 
        repo='ppa:ondrej/php' update_cache=yes
     when: ansible_distribution == 'Ubuntu'

#   - name: Add repository for PHP 5 compatibility packages (Ubuntu).
#     apt_repository: repo='ppa:ondrej/php5-compat'
#     when:
#       - php_version == "5.6"
#       - ansible_distribution == "Ubuntu"
#       - ansible_distribution_release != "bionic"

# Debian-specific tasks
   - name: Add dependencies for PHP versions (Debian).
     apt:
       name:
         - apt-transport-https
         - ca-certificates
       state: present
     become: true
     when: ansible_distribution == "Debian"

   - name: Add Ondrej Sury's apt key (Debian).
     apt_key:
       url: https://packages.sury.org/php/apt.gpg
       state: present
     become: true
     when: ansible_distribution == "Debian"

   - name: Add Ondrej Sury's repo (Debian).
     apt_repository:
       repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
       state: present
     register: php_ondrej_debian_repo
     become: true
     when: ansible_distribution == "Debian"

   - name: Update apt caches after repo is added (Debian).
     become: true
     apt: update_cache=yes
     when:
       - php_ondrej_debian_repo.changed
       - ansible_distribution == "Debian"
     tags: ['skip_ansible_lint']


# CentOS / RHEL specific tasks
   - name: add epel-release repo
     become: true
     yum_repository:
       name: epel
       description: EPEL YUM repo
       enabled: yes
       baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
#     yum: 
#        name: epel-release 
#        state: installed
#     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'

   - name: Add repository 'remi-repo'
     become: true
     yum:
       name: http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
       state: present
#     command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'



# Install php packages on Ubuntu / Debian
   - name: php5.6 on Ubuntu / Debian
     apt:
        name: php5.6
        state: present
     become: true
     when: version == "5.6" and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

   - name: php7.0 on Ubuntu / Debian
     apt:
        name: php7.0
        state: present
     become: true
     when: version == "7.0"  and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

   - name: php7.2 on Ubuntu / Debian
     apt:
        name: php7.2
        state: present
     become: true
     when: version == "7.2"  and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

   - name: install all php packages on Ubuntu / Debian
     apt: 
        name: "{{ items }}"
        state: present
     vars:
        items:           
        - php5.6      
        - php7.0
        - php7.2
        tags:
        - packages
     when: version == "all"  and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
     become: true   



# Install php packages on CentOS/RHEL
   - name: php5.6 on CentOS/RHEL
     yum:
        name: php
        enablerepo: 'remi-php56'
        state: present
     become: true
     when: version == "5.6" and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'   )

   - name: php7.0 on CentOS/RHEL
     yum:
        name: php
        enablerepo: 'remi-php70'
        state: present
     become: true
     when: version == "7.0"  and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'   )

   - name: php7.2 on CentOS/RHEL
     yum:
        name: php
        enablerepo: 'remi-php72'
        state: present
     become: true
     when: version == "7.2"  and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'   )

# the following should be tested later
   - name: install all php packages on CentOS/RHEL
     yum: 
        name: "{{ items }}"
        enablerepo: epel,remi
        state: present
     vars:
        items:           
        - php56      
        - php70
        - php72
        tags:
        - packages
     when: version == "all"  and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'   )
     become: true   
